name: 'Deploy Application/Service'
description: 'Deploy service'
inputs:
  enviroments: 
    description: 'Enviroment for usage'
    required: true
  ports: 
    required: true
runs:
    using: composite
    steps:
      - uses: actions/checkout@v6
        with: 
          repository: "mtararujs/python-greetings"
          clean: 'false'
          path: 'e2e-api-deploy'
      - name: delete existing
        working-directory: ./e2e-api-deploy
        run: pm2 delete greetings-app-${{ inputs.enviroments }} & EXIT /B 0
        shell: cmd

      - name: start new pm2
        working-directory: ./e2e-api-deploy
        ##run: pm2 start app.py --name greetings-app-${{ inputs.enviroments }} --interpreter python -- --port ${{ inputs.ports }}
        run: pm2 start app.py --name greetings-app-${{ inputs.enviroments }} --interpreter \venv\bin\python -- --port 4000
        shell: cmd