name: 'Deploy Application/Service'
description: 'Deploy service'
inputs:
  enviroments: 
    description: 'Enviroment for usage'
    required: true
  ports: 
    required: true
runs:
    using: composite
    steps:
      - uses: actions/checkout@v6
        with: 
          repository: "mtararujs/python-greetings"
          clean: 'false'
          path: 'e2e-api'
      - name: delete existing
        working-directory: ./e2e-api
        run: pm2 delete greetings-app-${{ inputs.environment }} || exit 0
        shell: cmd

      - name: start new pm2
        working-directory: ./e2e-api
        run: pm2 start app.py \"greetings-app-${{ inputs.environment }}\" --interpreter %CD%\\venv\\Scripts\\python.exe -- --port ${{ inputs.port }}
        shell: cmd