name: 'Run Application test'
description: 'Run test'
inputs:
  enviroments: 
    description: 'Enviroment for usage'
    required: true

runs:
    using: composite
    steps:
      - uses: actions/checkout@v6
        with: 
          repository: "mtararujs/python-greetings"
          clean: 'false'
          path: 'e2e-api-install'
      - name: Install on
        run: echo "Install to ${{ inputs.enviroments }}"
        shell: cmd

      - name: Create Enviroment
        working-directory: ./e2e-api-install
        run: python3 -m venv venv
        shell: cmd

      - name: activate enviroment
        working-directory: ./e2e-api-install  
        run:  ./venv/bin/python -m pip install -r requirements.txt
        shell: cmd
