name: 'Run Application test'
description: 'Run test'
inputs:
  enviroments: 
    description: 'Enviroment for usage'
    required: true

runs:
    using: composite
    steps:
      - uses: actions/checkout@v6
        with: 
          repository: "mtararujs/python-greetings"
          clean: 'false'
          path: 'e2e-api'
      - name: Install on
        run: echo "Install to ${{ inputs.enviroments }}"
        shell: cmd

      - name: Create Enviroment
        working-directory: ./e2e-api
        run: python3 -m venv venv
        shell: cmd
