name: github actions App Workflow

on: 
  push: 
    branches: ["main"]
  Workflow_dispatch:

jobs: 
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
      - name: install all dependencies
        run: npm install
  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to DEV enviroment has started.."
  test-on-dev: 
    runs-on: self-hosted
    needs: deploy-to-dev
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing in this step"
  deploy-to-stg:
    runs-on: self-hosted
    needs: test-on-dev
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  test-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to STG enviroment has started.."
  deploy-to-preprod: 
    runs-on: self-hosted
    needs: test-on-stg
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing in this step"
  test-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  deploy-to-prd:
    runs-on: self-hosted
    needs: test-on-preprod
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to PRD enviroment has started.."
  test-on-prd: 
    runs-on: self-hosted
    needs: deploy-to-prd
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing in this step"