name: github actions App Workflow

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs: 
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/install
        with:
          environments: "DEV"

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environments: "DEV"
          ports: 7001

  test-on-dev: 
    runs-on: self-hosted
    needs: deploy-to-dev
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environments: "DEV"

  deploy-to-stg:
    runs-on: self-hosted
    needs: test-on-dev
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environments: "STG"
          ports: 7002

  test-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environments: "STG"

  deploy-to-preprod: 
    runs-on: self-hosted
    needs: test-on-stg
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environments: "PREPROD"
          ports: 7003

  test-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environments: "PREPROD"

  deploy-to-prd:
    runs-on: self-hosted
    needs: test-on-preprod
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/deploy
        with:
          environments: "PRD"
          ports: 7004

  test-on-prd: 
    runs-on: self-hosted
    needs: deploy-to-prd
    steps: 
      - uses: actions/checkout@v6
      - uses: ./.github/actions/test
        with:
          environments: "PRD"