name: github actions App Workflow

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:

jobs: 
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps: 
      - uses: ./.github/actions/deploy
        with:
          enviroments: "DEV"
          ports: 7001
  test-on-dev: 
    runs-on: self-hosted
    needs: deploy-to-dev
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing DEV in this step"
  deploy-to-stg:
    runs-on: self-hosted
    needs: test-on-dev
    steps: 
      - uses: ./.github/actions/deploy
        with:
          enviroments: "STG"
          ports: 7002
  test-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing STG in this step"
  deploy-to-preprod: 
    runs-on: self-hosted
    needs: test-on-stg
    steps: 
      - uses: ./.github/actions/deploy
        with:
          enviroments: "PREPROD"
          ports: 7003
  test-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing PREPROD in this step"
  deploy-to-prd:
    runs-on: self-hosted
    needs: test-on-preprod
    steps: 
      - uses: ./.github/actions/deploy
        with:
          enviroments: "PRD"
          ports: 7004
  test-on-prd: 
    runs-on: self-hosted
    needs: deploy-to-prd
    steps: 
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing PRD in this step"